//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AltaTransport.WebRef_Korund {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SchetSoapBinding", Namespace="http://192.168.0.91")]
    public partial class Schet : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NewSchetOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewKontragentOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewDogovorOperationCompleted;
        
        private System.Threading.SendOrPostCallback OplataPoDogovoruOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaldoDogovoraOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Schet() {
            this.Url = global::AltaTransport.Properties.Settings.Default.AltaTransport_WebRef_Korund_Schet;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NewSchetCompletedEventHandler NewSchetCompleted;
        
        /// <remarks/>
        public event NewKontragentCompletedEventHandler NewKontragentCompleted;
        
        /// <remarks/>
        public event NewDogovorCompletedEventHandler NewDogovorCompleted;
        
        /// <remarks/>
        public event OplataPoDogovoruCompletedEventHandler OplataPoDogovoruCompleted;
        
        /// <remarks/>
        public event SaldoDogovoraCompletedEventHandler SaldoDogovoraCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.91#Schet:NewSchet", RequestNamespace="http://192.168.0.91", ResponseNamespace="http://192.168.0.91", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string NewSchet(string Zapros) {
            var results = this.Invoke("NewSchet", new object[] {
                        Zapros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NewSchetAsync(string Zapros) {
            this.NewSchetAsync(Zapros, null);
        }
        
        /// <remarks/>
        public void NewSchetAsync(string Zapros, object userState) {
            if ((this.NewSchetOperationCompleted == null)) {
                this.NewSchetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewSchetOperationCompleted);
            }
            this.InvokeAsync("NewSchet", new object[] {
                        Zapros}, this.NewSchetOperationCompleted, userState);
        }
        
        private void OnNewSchetOperationCompleted(object arg) {
            if ((this.NewSchetCompleted != null)) {
                var invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewSchetCompleted(this, new NewSchetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.91#Schet:NewKontragent", RequestNamespace="http://192.168.0.91", ResponseNamespace="http://192.168.0.91", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string NewKontragent(string Zapros) {
            var results = this.Invoke("NewKontragent", new object[] {
                        Zapros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NewKontragentAsync(string Zapros) {
            this.NewKontragentAsync(Zapros, null);
        }
        
        /// <remarks/>
        public void NewKontragentAsync(string Zapros, object userState) {
            if ((this.NewKontragentOperationCompleted == null)) {
                this.NewKontragentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewKontragentOperationCompleted);
            }
            this.InvokeAsync("NewKontragent", new object[] {
                        Zapros}, this.NewKontragentOperationCompleted, userState);
        }
        
        private void OnNewKontragentOperationCompleted(object arg) {
            if ((this.NewKontragentCompleted != null)) {
                var invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewKontragentCompleted(this, new NewKontragentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.91#Schet:NewDogovor", RequestNamespace="http://192.168.0.91", ResponseNamespace="http://192.168.0.91", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string NewDogovor(string Zapros) {
            var results = this.Invoke("NewDogovor", new object[] {
                        Zapros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NewDogovorAsync(string Zapros) {
            this.NewDogovorAsync(Zapros, null);
        }
        
        /// <remarks/>
        public void NewDogovorAsync(string Zapros, object userState) {
            if ((this.NewDogovorOperationCompleted == null)) {
                this.NewDogovorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewDogovorOperationCompleted);
            }
            this.InvokeAsync("NewDogovor", new object[] {
                        Zapros}, this.NewDogovorOperationCompleted, userState);
        }
        
        private void OnNewDogovorOperationCompleted(object arg) {
            if ((this.NewDogovorCompleted != null)) {
                var invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewDogovorCompleted(this, new NewDogovorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.91#Schet:OplataPoDogovoru", RequestNamespace="http://192.168.0.91", ResponseNamespace="http://192.168.0.91", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string OplataPoDogovoru(string Zapros) {
            var results = this.Invoke("OplataPoDogovoru", new object[] {
                        Zapros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OplataPoDogovoruAsync(string Zapros) {
            this.OplataPoDogovoruAsync(Zapros, null);
        }
        
        /// <remarks/>
        public void OplataPoDogovoruAsync(string Zapros, object userState) {
            if ((this.OplataPoDogovoruOperationCompleted == null)) {
                this.OplataPoDogovoruOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOplataPoDogovoruOperationCompleted);
            }
            this.InvokeAsync("OplataPoDogovoru", new object[] {
                        Zapros}, this.OplataPoDogovoruOperationCompleted, userState);
        }
        
        private void OnOplataPoDogovoruOperationCompleted(object arg) {
            if ((this.OplataPoDogovoruCompleted != null)) {
                var invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OplataPoDogovoruCompleted(this, new OplataPoDogovoruCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.91#Schet:SaldoDogovora", RequestNamespace="http://192.168.0.91", ResponseNamespace="http://192.168.0.91", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string SaldoDogovora(string Zapros) {
            var results = this.Invoke("SaldoDogovora", new object[] {
                        Zapros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoDogovoraAsync(string Zapros) {
            this.SaldoDogovoraAsync(Zapros, null);
        }
        
        /// <remarks/>
        public void SaldoDogovoraAsync(string Zapros, object userState) {
            if ((this.SaldoDogovoraOperationCompleted == null)) {
                this.SaldoDogovoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoDogovoraOperationCompleted);
            }
            this.InvokeAsync("SaldoDogovora", new object[] {
                        Zapros}, this.SaldoDogovoraOperationCompleted, userState);
        }
        
        private void OnSaldoDogovoraOperationCompleted(object arg) {
            if ((this.SaldoDogovoraCompleted != null)) {
                var invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoDogovoraCompleted(this, new SaldoDogovoraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            var wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void NewSchetCompletedEventHandler(object sender, NewSchetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewSchetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewSchetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void NewKontragentCompletedEventHandler(object sender, NewKontragentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewKontragentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewKontragentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void NewDogovorCompletedEventHandler(object sender, NewDogovorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewDogovorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewDogovorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void OplataPoDogovoruCompletedEventHandler(object sender, OplataPoDogovoruCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OplataPoDogovoruCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OplataPoDogovoruCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SaldoDogovoraCompletedEventHandler(object sender, SaldoDogovoraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoDogovoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoDogovoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591