//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltaMySqlDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class lots
    {
        public int id { get; set; }
        public Nullable<int> number { get; set; }
        public string description { get; set; }
        public string measure { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> start_price { get; set; }
        public Nullable<decimal> sum_price { get; set; }
        public string payment_term { get; set; }
        public string delivery_time { get; set; }
        public string delivery_place { get; set; }
        public Nullable<int> DKS { get; set; }
        public string contract_num { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> go { get; set; }
        public Nullable<int> contains { get; set; }
        public string amount_pr { get; set; }
        public string start_price_pr { get; set; }
        public Nullable<int> attachment { get; set; }
    
        public virtual auctions auctions { get; set; }
    }
}
